# NAME: SEBA SAUD

- Run: [**Open In Colab**](https://colab.research.google.com/github/HassanAlgoz/B5/blob/main/content/W3/M6/exercises/ex2_pycaret_classification.ipynb)

# M4.Ex2: Penguins Classification (PyCaret)

## Exercise

Your task is to follow the steps outlined here, and apply them on the **Palmer Penguins Dataset** below:

- [**🚀 Classification**](https://pycaret.gitbook.io/docs/get-started/quickstart#classification)
    - Setup
    - Compare Models
    - Analyze Model
    - Predictions
    - Save the model

## Palmer Penguins Dataset

The goal of palmer penguins is to provide a great dataset for data exploration & visualization, as an alternative to iris.

The data contains 344 penguins. There are 3 different species of penguins in this dataset, collected from 3 islands in the Palmer Archipelago, Antarctica.

- Features: `4` numerical, `2` categorical
- Target: `species` (Categorical / 3 classes)
- Size: `344` samples
- Source: [Palmer Penguins](https://allisonhorst.github.io/palmerpenguins/)

### Load the data

In [1]:
import seaborn as sns

penguins = sns.load_dataset('penguins')
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [ ]:

from sklearn.model_selection import train_test_split
from autogluon.tabular import TabularPredictor
data_exp1 = penguins[['flipper_length_mm', 'bill_length_mm', 'species']]
train_1, test_1 = train_test_split(data_exp1, test_size=0.2, random_state=42)
pred_1 = TabularPredictor(label='species').fit(train_1, time_limit=60, presets='medium_quality')
pred_1.leaderboard(test_1)

No path specified. Models will be saved in: "AutogluonModels\ag-20260422_080351"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.8
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       3.55 GB / 15.77 GB (22.5%)
Disk Space Avail:   163.26 GB / 475.71 GB (34.3%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "c:\Users\HP\OneDrive\Desktop\AAI\B5\student2\AutogluonModels\ag-20260422_080351"
Train Data Rows:    275
Train Data Columns: 2
Label Column:       species
AutoGluon infers your prediction problem is: 'multiclass' (because dtype of label-column == object).
	3 unique label values:  ['Adelie', 'Gentoo', 'Chinstrap']
	If 'multiclass' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       multiclass
Preprocessing data ...
Train Data Class Count: 3
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    3623.74 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 2 | ['flipper_length_mm', 'bill_length_mm']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 2 | ['flipper_length_mm', 'bill_length_mm']
	0.0s = Fit runtime
	2 features in original data used to generate 2 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.06s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 220, Val Rows: 55
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetFastAI ... Training model for up to 59.94s of the 59.94s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/3.5 GB
No improvement since epoch 2: early stopping
	0.9636	 = Validation score   (accuracy)
	1.89s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 58.02s of the 58.01s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/3.5 GB
	0.9455	 = Validation score   (accuracy)
	0.25s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 57.75s of the 57.75s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/3.5 GB
	0.9455	 = Validation score   (accuracy)
	0.23s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 57.50s of the 57.50s of remaining time.
	Fitting with cpus=8, gpus=0
	0.9455	 = Validation score   (accuracy)
	0.73s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 56.71s of the 56.71s of remaining time.
	Fitting with cpus=8, gpus=0
	0.9455	 = Validation score   (accuracy)
	0.51s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 56.14s of the 56.14s of remaining time.
	Fitting with cpus=4, gpus=0
	0.9636	 = Validation score   (accuracy)
	0.77s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 55.35s of the 55.35s of remaining time.
	Fitting with cpus=8, gpus=0
	0.9455	 = Validation score   (accuracy)
	0.52s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 54.77s of the 54.76s of remaining time.
	Fitting with cpus=8, gpus=0
	0.9455	 = Validation score   (accuracy)
	0.52s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 54.18s of the 54.18s of remaining time.
	Fitting with cpus=4, gpus=0
	0.9636	 = Validation score   (accuracy)
	0.25s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 53.90s of the 53.90s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/3.5 GB
c:\Users\HP\OneDrive\Desktop\AAI\B5\Student\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	0.9636	 = Validation score   (accuracy)
	2.28s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 51.60s of the 51.60s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.2/3.5 GB
	0.9273	 = Validation score   (accuracy)
	0.5s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.94s of the 51.07s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/3.5 GB
	Ensemble Weights: {'NeuralNetFastAI': 1.0}
	0.9636	 = Validation score   (accuracy)
	0.08s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 9.12s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 7164.6 rows/s (55 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\HP\OneDrive\Desktop\AAI\B5\student2\AutogluonModels\ag-20260422_080351")

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,RandomForestGini,0.971014,0.945455,accuracy,0.070132,0.038654,0.725851,0.070132,0.038654,0.725851,1,True,4
1,CatBoost,0.956522,0.963636,accuracy,0.004178,0.000000,0.774792,0.004178,0.000000,0.774792,1,True,6
2,RandomForestEntr,0.956522,0.945455,accuracy,0.062443,0.038920,0.509526,0.062443,0.038920,0.509526,1,True,5
3,NeuralNetTorch,0.942029,0.963636,accuracy,0.010851,0.000000,2.284932,0.010851,0.000000,2.284932,1,True,10
4,NeuralNetFastAI,0.942029,0.963636,accuracy,0.013273,0.007677,1.887415,0.013273,0.007677,1.887415,1,True,1
5,WeightedEnsemble_L2,0.942029,0.963636,accuracy,0.015276,0.007677,1.963530,0.002003,0.000000,0.076115,2,True,12
6,ExtraTreesEntr,0.942029,0.945455,accuracy,0.046041,0.036492,0.521689,0.046041,0.036492,0.521689,1,True,8
7,ExtraTreesGini,0.927536,0.945455,accuracy,0.058631,0.039209,0.520432,0.058631,0.039209,0.520432,1,True,7
8,LightGBM,0.913043,0.945455,accuracy,0.003954,0.000000,0.234608,0.003954,0.000000,0.234608,1,True,3
9,LightGBMXT,0.898551,0.945455,accuracy,0.015134,0.004915,0.246857,0.015134,0.004915,0.246857,1,True,2
10,XGBoost,0.898551,0.963636,accuracy,0.016172,0.000000,0.249964,0.016172,0.000000,0.249964,1,True,9
11,LightGBMLarge,0.884058,0.927273,accuracy,0.002004,0.000000,0.501707,0.002004,0.000000,0.501707,1,True,11

## Experiments

1. **First experiment**:
    - X = Flipper Length (numerical) & Bill Length (numerical)
    - y = Species (categorical)
2. **Second experiment**:
    - X = Weights (numerical) & Species (categorical)
    - y = Sex (categroical)
3. **Third experiment**:
    - X = `island`, `bill_length_mm`, `bill_depth_mm`, `flipper_length_mm`, `body_mass_g`
    - y = Sex and Species (multi-label classification)

In [ ]:

data_exp1 = penguins[['flipper_length_mm', 'bill_length_mm', 'species']]
train_1, test_1 = train_test_split(data_exp1, test_size=0.2, random_state=42)
pred_1 = TabularPredictor(label='species').fit(train_1, time_limit=60, presets='medium_quality')
pred_1.leaderboard(test_1)

No path specified. Models will be saved in: "AutogluonModels\ag-20260422_080405"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.8
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       3.47 GB / 15.77 GB (22.0%)
Disk Space Avail:   163.25 GB / 475.71 GB (34.3%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "c:\Users\HP\OneDrive\Desktop\AAI\B5\student2\AutogluonModels\ag-20260422_080405"
Train Data Rows:    275
Train Data Columns: 2
Label Column:       species
AutoGluon infers your prediction problem is: 'multiclass' (because dtype of label-column == object).
	3 unique label values:  ['Adelie', 'Gentoo', 'Chinstrap']
	If 'multiclass' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       multiclass
Preprocessing data ...
Train Data Class Count: 3
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    3548.65 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 2 | ['flipper_length_mm', 'bill_length_mm']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 2 | ['flipper_length_mm', 'bill_length_mm']
	0.0s = Fit runtime
	2 features in original data used to generate 2 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.05s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 220, Val Rows: 55
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetFastAI ... Training model for up to 59.95s of the 59.95s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/3.5 GB
No improvement since epoch 2: early stopping
	0.9636	 = Validation score   (accuracy)
	0.93s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 58.99s of the 58.99s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/3.5 GB
	0.9455	 = Validation score   (accuracy)
	0.2s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 58.77s of the 58.77s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/3.5 GB
	0.9455	 = Validation score   (accuracy)
	0.24s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 58.51s of the 58.51s of remaining time.
	Fitting with cpus=8, gpus=0
	0.9455	 = Validation score   (accuracy)
	0.53s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 57.92s of the 57.92s of remaining time.
	Fitting with cpus=8, gpus=0
	0.9455	 = Validation score   (accuracy)
	0.51s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 57.35s of the 57.34s of remaining time.
	Fitting with cpus=4, gpus=0
	0.9636	 = Validation score   (accuracy)
	0.71s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 56.63s of the 56.63s of remaining time.
	Fitting with cpus=8, gpus=0
	0.9455	 = Validation score   (accuracy)
	0.53s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 56.04s of the 56.03s of remaining time.
	Fitting with cpus=8, gpus=0
	0.9455	 = Validation score   (accuracy)
	0.55s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 55.43s of the 55.43s of remaining time.
	Fitting with cpus=4, gpus=0
	0.9636	 = Validation score   (accuracy)
	0.15s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 55.25s of the 55.25s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/3.5 GB
c:\Users\HP\OneDrive\Desktop\AAI\B5\Student\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	0.9636	 = Validation score   (accuracy)
	0.71s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 54.53s of the 54.53s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.2/3.5 GB
	0.9273	 = Validation score   (accuracy)
	0.43s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.95s of the 54.07s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/3.5 GB
	Ensemble Weights: {'NeuralNetFastAI': 1.0}
	0.9636	 = Validation score   (accuracy)
	0.09s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 6.06s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 7842.2 rows/s (55 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\HP\OneDrive\Desktop\AAI\B5\student2\AutogluonModels\ag-20260422_080405")

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,RandomForestGini,0.971014,0.945455,accuracy,0.064191,0.039560,0.531034,0.064191,0.039560,0.531034,1,True,4
1,CatBoost,0.956522,0.963636,accuracy,0.004424,0.000000,0.705426,0.004424,0.000000,0.705426,1,True,6
2,RandomForestEntr,0.956522,0.945455,accuracy,0.062680,0.040804,0.507427,0.062680,0.040804,0.507427,1,True,5
3,NeuralNetTorch,0.942029,0.963636,accuracy,0.008016,0.002003,0.706865,0.008016,0.002003,0.706865,1,True,10
4,NeuralNetFastAI,0.942029,0.963636,accuracy,0.016152,0.006014,0.934310,0.016152,0.006014,0.934310,1,True,1
5,WeightedEnsemble_L2,0.942029,0.963636,accuracy,0.018157,0.007013,1.021070,0.002005,0.000999,0.086760,2,True,12
6,ExtraTreesEntr,0.942029,0.945455,accuracy,0.049089,0.039855,0.547438,0.049089,0.039855,0.547438,1,True,8
7,ExtraTreesGini,0.927536,0.945455,accuracy,0.048647,0.040092,0.529975,0.048647,0.040092,0.529975,1,True,7
8,LightGBM,0.913043,0.945455,accuracy,0.007544,0.002009,0.244305,0.007544,0.002009,0.244305,1,True,3
9,LightGBMXT,0.898551,0.945455,accuracy,0.000000,0.000000,0.200726,0.000000,0.000000,0.200726,1,True,2
10,XGBoost,0.898551,0.963636,accuracy,0.016359,0.000000,0.150174,0.016359,0.000000,0.150174,1,True,9
11,LightGBMLarge,0.884058,0.927273,accuracy,0.003754,0.003769,0.428133,0.003754,0.003769,0.428133,1,True,11

In [ ]:
data_exp2 = penguins[['body_mass_g', 'species', 'sex']]
data_exp2 = data_exp2.dropna(subset=['sex'])
from sklearn.model_selection import train_test_split
train_2, test_2 = train_test_split(data_exp2, test_size=0.2, random_state=42)
from autogluon.tabular import TabularPredictor
pred_2 = TabularPredictor(label='sex').fit(train_2, time_limit=60, presets='medium_quality')
pred_2.leaderboard(test_2)

No path specified. Models will be saved in: "AutogluonModels\ag-20260422_080503"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.8
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       3.30 GB / 15.77 GB (20.9%)
Disk Space Avail:   163.24 GB / 475.71 GB (34.3%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "c:\Users\HP\OneDrive\Desktop\AAI\B5\student2\AutogluonModels\ag-20260422_080503"
Train Data Rows:    266
Train Data Columns: 2
Label Column:       sex
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['Female', 'Male']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = Male, class 0 = Female
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (Male) vs negative (Female) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    3380.84 MB
	Train Data (Original)  Memory Usage: 0.02 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 1 | ['body_mass_g']
		('object', []) : 1 | ['species']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 1 | ['species']
		('float', [])    : 1 | ['body_mass_g']
	0.0s = Fit runtime
	2 features in original data used to generate 2 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.06s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 212, Val Rows: 54
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ... Training model for up to 59.94s of the 59.94s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/3.3 GB
	0.8148	 = Validation score   (accuracy)
	0.19s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 59.71s of the 59.71s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/3.3 GB
	0.8148	 = Validation score   (accuracy)
	0.2s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 59.48s of the 59.48s of remaining time.
	Fitting with cpus=8, gpus=0
	0.7593	 = Validation score   (accuracy)
	0.52s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 58.89s of the 58.89s of remaining time.
	Fitting with cpus=8, gpus=0
	0.7593	 = Validation score   (accuracy)
	0.53s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 58.32s of the 58.32s of remaining time.
	Fitting with cpus=4, gpus=0
	0.8148	 = Validation score   (accuracy)
	11.33s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 46.97s of the 46.97s of remaining time.
	Fitting with cpus=8, gpus=0
	0.7593	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 46.41s of the 46.41s of remaining time.
	Fitting with cpus=8, gpus=0
	0.7593	 = Validation score   (accuracy)
	0.5s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 45.85s of the 45.85s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/3.3 GB
No improvement since epoch 7: early stopping
	0.8148	 = Validation score   (accuracy)
	1.32s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 44.49s of the 44.49s of remaining time.
	Fitting with cpus=4, gpus=0
	0.8148	 = Validation score   (accuracy)
	0.2s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 44.26s of the 44.26s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/3.3 GB
c:\Users\HP\OneDrive\Desktop\AAI\B5\Student\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	0.8333	 = Validation score   (accuracy)
	0.74s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 43.51s of the 43.51s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.1/3.4 GB
	0.7778	 = Validation score   (accuracy)
	0.33s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.94s of the 43.15s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/3.4 GB
	Ensemble Weights: {'NeuralNetTorch': 1.0}
	0.8333	 = Validation score   (accuracy)
	0.09s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 17.05s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 8970.0 rows/s (54 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (54 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\HP\OneDrive\Desktop\AAI\B5\student2\AutogluonModels\ag-20260422_080503")

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,NeuralNetFastAI,0.880597,0.814815,accuracy,0.022889,0.012415,1.322404,0.022889,0.012415,1.322404,1,True,8
1,LightGBMXT,0.865672,0.814815,accuracy,0.002015,0.003727,0.186216,0.002015,0.003727,0.186216,1,True,1
2,LightGBM,0.865672,0.814815,accuracy,0.004013,0.004993,0.196238,0.004013,0.004993,0.196238,1,True,2
3,CatBoost,0.865672,0.814815,accuracy,0.004910,0.000000,11.332890,0.004910,0.000000,11.332890,1,True,5
4,RandomForestGini,0.865672,0.759259,accuracy,0.071803,0.040839,0.523287,0.071803,0.040839,0.523287,1,True,3
5,ExtraTreesGini,0.865672,0.759259,accuracy,0.071833,0.042379,0.489659,0.071833,0.042379,0.489659,1,True,6
6,RandomForestEntr,0.865672,0.759259,accuracy,0.076180,0.027725,0.530126,0.076180,0.027725,0.530126,1,True,4
7,ExtraTreesEntr,0.865672,0.759259,accuracy,0.080308,0.039890,0.501011,0.080308,0.039890,0.501011,1,True,7
8,NeuralNetTorch,0.850746,0.833333,accuracy,0.008027,0.006020,0.735332,0.008027,0.006020,0.735332,1,True,10
9,WeightedEnsemble_L2,0.850746,0.833333,accuracy,0.011027,0.006020,0.824295,0.003001,0.000000,0.088962,2,True,12
10,LightGBMLarge,0.835821,0.777778,accuracy,0.007667,0.004019,0.328507,0.007667,0.004019,0.328507,1,True,11
11,XGBoost,0.835821,0.814815,accuracy,0.013002,0.008067,0.201789,0.013002,0.008067,0.201789,1,True,9

In [7]:

features = ['island', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']

print("TYPE OF FEATURES: ", type(features))
data_3a = penguins[features + ['species']].dropna()
train_3a, test_3a = train_test_split(data_3a, test_size=0.2, random_state=42)
pred_3a = TabularPredictor(label='species').fit(train_3a, time_limit=30, presets='medium_quality')
pred_3a.leaderboard(test_3a)

print("\n GENDER")
data_3b = penguins[features + ['sex']].dropna()
train_3b, test_3b = train_test_split(data_3b, test_size=0.2, random_state=42)
pred_3b = TabularPredictor(label='sex').fit(train_3b, time_limit=30, presets='medium_quality')
pred_3b.leaderboard(test_3b)

No path specified. Models will be saved in: "AutogluonModels\ag-20260422_081111"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.8
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       2.86 GB / 15.77 GB (18.1%)
Disk Space Avail:   163.21 GB / 475.71 GB (34.3%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'

TYPE OF FEATURES:  <class 'list'>

Beginning AutoGluon training ... Time limit = 30s
AutoGluon will save models to "c:\Users\HP\OneDrive\Desktop\AAI\B5\student2\AutogluonModels\ag-20260422_081111"
Train Data Rows:    273
Train Data Columns: 5
Label Column:       species
AutoGluon infers your prediction problem is: 'multiclass' (because dtype of label-column == object).
	3 unique label values:  ['Adelie', 'Gentoo', 'Chinstrap']
	If 'multiclass' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       multiclass
Preprocessing data ...
Train Data Class Count: 3
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    2911.10 MB
	Train Data (Original)  Memory Usage: 0.02 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 4 | ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']
		('object', []) : 1 | ['island']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 1 | ['island']
		('float', [])    : 4 | ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']
	0.0s = Fit runtime
	5 features in original data used to generate 5 features in processed data.
	Train Data (Processed) Memory Usage: 0.01 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.06s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 218, Val Rows: 55
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetFastAI ... Training model for up to 29.94s of the 29.94s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/2.8 GB
No improvement since epoch 7: early stopping
	1.0	 = Validation score   (accuracy)
	1.56s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 28.34s of the 28.34s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/2.8 GB
	1.0	 = Validation score   (accuracy)
	0.24s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 28.08s of the 28.08s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/2.8 GB
	1.0	 = Validation score   (accuracy)
	0.27s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 27.79s of the 27.79s of remaining time.
	Fitting with cpus=8, gpus=0
	0.9818	 = Validation score   (accuracy)
	0.65s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 27.08s of the 27.08s of remaining time.
	Fitting with cpus=8, gpus=0
	0.9818	 = Validation score   (accuracy)
	0.54s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 26.48s of the 26.48s of remaining time.
	Fitting with cpus=4, gpus=0
	1.0	 = Validation score   (accuracy)
	12.32s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 14.14s of the 14.14s of remaining time.
	Fitting with cpus=8, gpus=0
	1.0	 = Validation score   (accuracy)
	0.56s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 13.53s of the 13.53s of remaining time.
	Fitting with cpus=8, gpus=0
	1.0	 = Validation score   (accuracy)
	0.65s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 12.83s of the 12.83s of remaining time.
	Fitting with cpus=4, gpus=0
	1.0	 = Validation score   (accuracy)
	0.11s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 12.69s of the 12.69s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/2.8 GB
c:\Users\HP\OneDrive\Desktop\AAI\B5\Student\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	1.0	 = Validation score   (accuracy)
	0.84s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 11.83s of the 11.83s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.2/2.8 GB
	1.0	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 29.94s of the 11.31s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/2.8 GB
	Ensemble Weights: {'XGBoost': 1.0}
	1.0	 = Validation score   (accuracy)
	0.08s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 18.8s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 9140.8 rows/s (55 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\HP\OneDrive\Desktop\AAI\B5\student2\AutogluonModels\ag-20260422_081111")
No path specified. Models will be saved in: "AutogluonModels\ag-20260422_081131"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.8
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          8
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       2.80 GB / 15.77 GB (17.8%)
Disk Space Avail:   163.20 GB / 475.71 GB (34.3%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'

 GENDER

Beginning AutoGluon training ... Time limit = 30s
AutoGluon will save models to "c:\Users\HP\OneDrive\Desktop\AAI\B5\student2\AutogluonModels\ag-20260422_081131"
Train Data Rows:    266
Train Data Columns: 5
Label Column:       sex
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['Female', 'Male']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = Male, class 0 = Female
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (Male) vs negative (Female) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    2865.03 MB
	Train Data (Original)  Memory Usage: 0.02 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 4 | ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']
		('object', []) : 1 | ['island']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 1 | ['island']
		('float', [])    : 4 | ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']
	0.0s = Fit runtime
	5 features in original data used to generate 5 features in processed data.
	Train Data (Processed) Memory Usage: 0.01 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.06s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 212, Val Rows: 54
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ... Training model for up to 29.94s of the 29.93s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/2.8 GB
	0.9259	 = Validation score   (accuracy)
	0.19s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 29.73s of the 29.72s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/2.8 GB
	0.9074	 = Validation score   (accuracy)
	0.22s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 29.49s of the 29.48s of remaining time.
	Fitting with cpus=8, gpus=0
	0.9074	 = Validation score   (accuracy)
	0.55s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 28.89s of the 28.89s of remaining time.
	Fitting with cpus=8, gpus=0
	0.9259	 = Validation score   (accuracy)
	0.48s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 28.36s of the 28.36s of remaining time.
	Fitting with cpus=4, gpus=0
	0.9444	 = Validation score   (accuracy)
	12.44s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 15.91s of the 15.90s of remaining time.
	Fitting with cpus=8, gpus=0
	0.9074	 = Validation score   (accuracy)
	0.54s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 15.30s of the 15.30s of remaining time.
	Fitting with cpus=8, gpus=0
	0.9074	 = Validation score   (accuracy)
	0.58s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 14.66s of the 14.66s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/2.8 GB
	0.9259	 = Validation score   (accuracy)
	1.65s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 12.97s of the 12.97s of remaining time.
	Fitting with cpus=4, gpus=0
	0.9259	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 12.80s of the 12.80s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.0/2.8 GB
c:\Users\HP\OneDrive\Desktop\AAI\B5\Student\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	0.9074	 = Validation score   (accuracy)
	1.36s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 11.42s of the 11.42s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.1/2.9 GB
	0.9074	 = Validation score   (accuracy)
	0.39s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 29.94s of the 10.97s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/2.9 GB
	Ensemble Weights: {'CatBoost': 1.0}
	0.9444	 = Validation score   (accuracy)
	0.07s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 19.16s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 1024.0 rows/s (54 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (54 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\HP\OneDrive\Desktop\AAI\B5\student2\AutogluonModels\ag-20260422_081131")

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,ExtraTreesGini,0.925373,0.907407,accuracy,0.054189,0.039880,0.538527,0.054189,0.039880,0.538527,1,True,6
1,LightGBMLarge,0.910448,0.907407,accuracy,0.002008,0.004010,0.386311,0.002008,0.004010,0.386311,1,True,11
2,NeuralNetFastAI,0.910448,0.925926,accuracy,0.015483,0.013290,1.650205,0.015483,0.013290,1.650205,1,True,8
3,ExtraTreesEntr,0.910448,0.907407,accuracy,0.050376,0.041796,0.576149,0.050376,0.041796,0.576149,1,True,7
4,CatBoost,0.895522,0.944444,accuracy,0.000000,0.000000,12.436839,0.000000,0.000000,12.436839,1,True,5
5,WeightedEnsemble_L2,0.895522,0.944444,accuracy,0.003094,0.000000,12.507321,0.003094,0.000000,0.070482,2,True,12
6,NeuralNetTorch,0.895522,0.907407,accuracy,0.010562,0.005493,1.359849,0.010562,0.005493,1.359849,1,True,10
7,RandomForestEntr,0.895522,0.925926,accuracy,0.054043,0.027453,0.477069,0.054043,0.027453,0.477069,1,True,4
8,RandomForestGini,0.895522,0.907407,accuracy,0.074588,0.027328,0.545044,0.074588,0.027328,0.545044,1,True,3
9,LightGBM,0.880597,0.907407,accuracy,0.002998,0.000000,0.221145,0.002998,0.000000,0.221145,1,True,2
10,XGBoost,0.880597,0.925926,accuracy,0.012496,0.009055,0.139066,0.012496,0.009055,0.139066,1,True,9
11,LightGBMXT,0.820896,0.925926,accuracy,0.003921,0.000000,0.191322,0.003921,0.000000,0.191322,1,True,1